/*
 * This file is generated by jOOQ.
*/
package myeslib3.example1.datamodel;


import myeslib3.example1.datamodel.tables.AggregateRoots;
import myeslib3.example1.datamodel.tables.Idempotency;
import myeslib3.example1.datamodel.tables.SchemaVersion;
import myeslib3.example1.datamodel.tables.UnitsOfWork;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in example1db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>example1db.aggregate_roots</code>.
     */
    public static final AggregateRoots AGGREGATE_ROOTS = myeslib3.example1.datamodel.tables.AggregateRoots.AGGREGATE_ROOTS;

    /**
     * The table <code>example1db.idempotency</code>.
     */
    public static final Idempotency IDEMPOTENCY = myeslib3.example1.datamodel.tables.Idempotency.IDEMPOTENCY;

    /**
     * The table <code>example1db.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = myeslib3.example1.datamodel.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>example1db.units_of_work</code>.
     */
    public static final UnitsOfWork UNITS_OF_WORK = myeslib3.example1.datamodel.tables.UnitsOfWork.UNITS_OF_WORK;
}
